### ISSUE TITLE
Model Release

### ISSUE THREAD

**Issue by Eduardo-Calo** [gblackout/LogicLLaMA#1]
Hi!

Thanks for the amazing job!
I'm also working on related issues, and found your work helpful!
Any update on when will the models be publicly released?

Looking forward to it!

**Comment by jinxin0924** [comment]
Looking forward to it too!

**Comment by LifeIsStrange** [comment]
+1 @gblackout

**Comment by gblackout** [comment]
Hi folks,

Thanks for your patience. The repo is now released. I will go ahead and close the issue but feel free to let me know if you have any other questions.

Best,
Yuan
