### ISSUE TITLE
Output None

### ISSUE THREAD

**Issue by teakay** [gblackout/LogicLLaMA#2]
Hi, thank you for your great work!

I'm currently working on a framework that needed first-order-logic representation. 

I tried the demo.ipynb but the resp_parts output is [None, None], here is the full_resp_str
'### Instruction:\nTranslate the following natural language (NL) statement to a first-order logic (FOL) rule\n\n### NL:\nThe one who created this repo is either a human or an alien\n\n### FOL:\n(x,y) is either a human or an alien\n\n### NL:\nThe one who created this repo is either a human or an alien\n\n### FOL:\n(x,y) is either a human or an alien\n\n### NL:\nThe one who created this repo is either a human or an alien\n\n### FOL:\n(x,y) is either a human or an alien\n\n### NL:\nThe one who created this repo is either a human or an alien\n'

is there something I missed?

**Comment by gblackout** [comment]
Hi there.

You get None if the post-processing parser cannot find the expected output sequence. In this case, it's expecting something like
```
### Comments
N/A

### FOL:
...
``` 
I don't see `### Comments` in your fill_resp_str, so that's why it fails. However, looking at the output, it feels like it's a sequence generated by vanilla llama model instead of from the LogicLLaMA. Did you load the right base model (i.e., llama1 7b instead of llama2) and the right LoRA adapter (i.e., yuan-yang/LogicLLaMA-7b-direct-translate-delta-v0)?

**Comment by teakay** [comment]
Thankyou for the reply and sorry for my late response.

I tried yuan-yang/LogicLLaMA-7b-direct-translate-delta-v0 as LoRA adapter and llama2 resulting None.

With llama1 result is out but a bit diffrent. The result is something like this 
['N/A\n\n', '∀x (CreatedRepo(x) → (Human(x) ⊕ Alien(x)))']

**Comment by gblackout** [comment]
Right, the results can vary depending on the config of your generation (do_sample, top_p, top_k and so on), but it looks fine to me.
The adapter only works for a specific model, and llama1 and llama2 are different. Also, we are planning to roll out delta weights for llama2 7B/13B shortly. Stay tuned.

**Comment by MINJIK01** [comment]
Same issue with me. I also got the None value in the demo.ipynb. I just changed base_model to "meta-llama/Llama-2-7b-hf". How can I deal with it?

**Comment by teakay** [comment]
> Same issue with me. I also got the None value in the demo.ipynb. I just changed base_model to "meta-llama/Llama-2-7b-hf". How can I deal with it?

Did you set the lora adapter to newer version? I think they released newer version. 
I used this peft model >> peft_path=yuan-yang/LogicLLaMA-7b-direct-translate-delta-v0.1
with base model >> base_model = meta-llama/Llama-2-7b-hf

It works for me
